### ISSUE TITLE
Add team members details

### ISSUE THREAD

**Issue by symeneses** [data-umbrella/data-umbrella-website#15]
This will be added in the about us page. 
We can add the following details:
```yaml
  - name: "Gibson Robert"
    designation: "Financial Analyst"
    description: "Nullam id dolor id nibh ultricies vehicula ut id elit. Cras mattis consectetur purus amet."
    image: "/assets/images/art/te1.jpg"
    social_icons:
      - icon: "jam jam-facebook"
        url: "https://facebook.com"
      - icon: "jam jam-twitter"
        url: "#"
      - icon: "jam jam-instagram"
        url: "#"
   ```
